# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cadastroCorridas.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(453, 328)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 10, 441, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 90, 47, 13))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 120, 81, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 150, 101, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 180, 121, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(20, 210, 121, 16))
        self.label_7.setObjectName("label_7")
        self.nome = QtWidgets.QLineEdit(self.centralwidget)
        self.nome.setGeometry(QtCore.QRect(60, 50, 341, 20))
        self.nome.setObjectName("nome")
        self.cidade = QtWidgets.QLineEdit(self.centralwidget)
        self.cidade.setGeometry(QtCore.QRect(60, 80, 341, 20))
        self.cidade.setObjectName("cidade")
        self.dataprova = QtWidgets.QLineEdit(self.centralwidget)
        self.dataprova.setGeometry(QtCore.QRect(99, 113, 171, 20))
        self.dataprova.setObjectName("dataprova")
        self.datalimite = QtWidgets.QLineEdit(self.centralwidget)
        self.datalimite.setGeometry(QtCore.QRect(139, 174, 171, 20))
        self.datalimite.setObjectName("datalimite")
        self.valorinscricao = QtWidgets.QLineEdit(self.centralwidget)
        self.valorinscricao.setGeometry(QtCore.QRect(110, 144, 171, 20))
        self.valorinscricao.setObjectName("valorinscricao")
        self.link = QtWidgets.QLineEdit(self.centralwidget)
        self.link.setGeometry(QtCore.QRect(113, 205, 331, 20))
        self.link.setObjectName("link")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(190, 260, 75, 23))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "CADASTRO DE CORRIDAS"))
        self.label_2.setText(_translate("MainWindow", "Nome:"))
        self.label_3.setText(_translate("MainWindow", "Cidade:"))
        self.label_4.setText(_translate("MainWindow", "Data da prova:"))
        self.label_5.setText(_translate("MainWindow", "Valor da inscrição:"))
        self.label_6.setText(_translate("MainWindow", "Data limite da inscrição:"))
        self.label_7.setText(_translate("MainWindow", "Link para inscrição:"))
        self.pushButton.setText(_translate("MainWindow", "SALVAR"))
